repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
  - repo: https://github.com/Zac-HD/shed
    rev: 2024.3.1
    hooks:
      - id: shed
        args: [--refactor, --py312-plus]
        types_or: [python, pyi, markdown, rst]
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: node
        pass_filenames: false
        types: [python]
        additional_dependencies: ["pyright"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
