openapi: 3.1.0
info:
  title: FTCB API
  version: 0.0.0-alpha
paths:
  /api/health:
    get:
      description: ''
      parameters: []
      operationId: health
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'
  /api/requested_task:
    get:
      description: ''
      parameters: []
      operationId: find_all_requested_tasks
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HydratedRequestedTask'
        '404':
          description: ''
          content:
            application/json:
              schema:
                type: string
    post:
      description: ''
      parameters: []
      operationId: created_requested_task
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HydratedRequestedTask'
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRequestedTask'
    put:
      description: ''
      parameters: []
      operationId: update_requested_task
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HydratedRequestedTask'
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRequestedTask'
  /api/requested_task/{id}:
    get:
      description: Find the requested task if it exists.
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: The id of the task to find
      operationId: find_requested_task_by_id
      responses:
        '200':
          description: Requested task with id successfully found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HydratedRequestedTask'
        '404':
          description: Requested task with id not found.
          content:
            application/json:
              schema:
                type: string
    delete:
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: ''
      operationId: remove_requested_task
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HydratedRequestedTask'
  /api/requested_task/schedule:
    post:
      description: Schedule list of tasks by their ids.
      parameters: []
      operationId: schedule_requested_tasks
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HydratedRequestedTask'
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
servers: []
components:
  schemas:
    HealthStatus:
      title: HealthStatus
      type: object
      properties:
        status:
          type: string
      required:
      - status
    HydratedRequestedTask:
      title: HydratedRequestedTask
      type: object
      properties:
        id:
          type: integer
        department:
          type: string
        den:
          type: string
        nature_of_work:
          type: string
        block:
          type: string
        location:
          type: string
        preferred_starts_at:
          type: string
        preferred_ends_at:
          type: string
        requested_date:
          type: string
          format: date
        requested_duration:
          type: string
          format: duration
        priority:
          type: integer
        section_id:
          type: integer
      required:
      - id
      - department
      - den
      - nature_of_work
      - block
      - location
      - preferred_starts_at
      - preferred_ends_at
      - requested_date
      - requested_duration
      - priority
      - section_id
    CreateRequestedTask:
      title: CreateRequestedTask
      type: object
      properties:
        id:
          anyOf:
          - type: integer
          - type: 'null'
          default: null
        department:
          type: string
        den:
          type: string
        nature_of_work:
          type: string
        block:
          type: string
        location:
          type: string
        preferred_starts_at:
          type: string
        preferred_ends_at:
          type: string
        requested_date:
          type: string
          format: date
        requested_duration:
          type: string
          format: duration
        priority:
          type: integer
        section_id:
          type: integer
      required:
      - department
      - den
      - nature_of_work
      - block
      - location
      - preferred_starts_at
      - preferred_ends_at
      - requested_date
      - requested_duration
      - priority
      - section_id
    UpdateRequestedTask:
      title: UpdateRequestedTask
      type: object
      properties:
        id:
          type: integer
        department:
          type: string
        den:
          type: string
        nature_of_work:
          type: string
        block:
          type: string
        location:
          type: string
        preferred_starts_at:
          type: string
        preferred_ends_at:
          type: string
        requested_date:
          type: string
          format: date
        requested_duration:
          type: string
          format: duration
        priority:
          type: integer
        section_id:
          type: integer
      required:
      - id
      - department
      - den
      - nature_of_work
      - block
      - location
      - preferred_starts_at
      - preferred_ends_at
      - requested_date
      - requested_duration
      - priority
      - section_id
  parameters: {}
